version: '3.8'

services:
  airbnb-predictor:
    build:
      context: .
      dockerfile: Dockerfile
    image: airbnb-predictor:latest
    container_name: airbnb-predictor
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./airbnb:/app/airbnb
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - DEBUG=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - airbnb-network

networks:
  airbnb-network:
    driver: bridge